# Generated by Django 5.2 on 2025-04-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('Sydney', 'Sydney'), ('Melbourne', 'Melbourne'), ('Brisbane', 'Brisbane'), ('Adelaide', 'Adelaide'), ('Perth', 'Perth'), ('Hobart', 'Hobart'), ('Darwin', 'Darwin'), ('Canberra', 'Canberra')], max_length=255)),
                ('event_category', models.CharField(choices=[('Music', 'Music'), ('Nightlife', 'Nightlife'), ('Performing & Visual Arts', 'Arts'), ('Holidays', 'Holidays'), ('Dating', 'Dating'), ('Hobbies', 'Hobbies'), ('Business', 'Business'), ('Food & Drink', 'Food Drink')], max_length=255)),
                ('event_mode', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
