# Generated by Django 5.2 on 2025-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
