# Generated by Django 5.2 on 2025-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
