# Generated by Django 5.2 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="number_of_bookings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
